create table members
(MEMBER_ID CHAR(8) PRIMARY KEY NOT NULL,
MEMBER_PASSWORD VARCHAR2 (30) NOT NULL,
BIRTHDAY DATE NOT NULL,
MEMBER_SURNAME VARCHAR2(30) NOT NULL,
MEMBER_LASTNAME VARCHAR2(30) NOT NULL,
SEX CHAR(1) NOT NULL,
MEMBER_TEL CHAR(8) NOT NULL);